language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head
  - rbx-19mode
  - jruby
  - jruby-head
jdk:
  - oraclejdk7
  - openjdk7
script: bundle exec rake spec
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head